# Generated by Django 2.2.6 on 2021-07-13 14:55

import django.core.validators
from django.db import migrations, models
import lib.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1984), lib.models.max_value_current_year])),
                ('artist', models.CharField(max_length=64)),
                ('genre', models.CharField(max_length=64)),
                ('album', models.CharField(max_length=64)),
            ],
        ),
    ]
