# Generated by Django 2.2.6 on 2021-07-13 15:47

import django.core.validators
from django.db import migrations, models
import lib.models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1940), lib.models.max_value_current_year]),
        ),
    ]
